[package]
name = "canparser"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "Parsing of CAN data based on a DBC file."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
can-dbc = "5.0.0"
num = "0.4.1"
